site_name: Go Documentation Map
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Переключить на тёмную тему
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
  features:
    - palette.toggle
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Введение:
      - Философия Go: intro/philosophy.md
      - Helicopter view: intro/helicopter-view.md
      - Работа с документацией: intro/docs.md
  - Основы языка:
      - Синтаксис: basics/syntax.md
      - Переменные и типы: basics/variables.md
      - Функции и методы: basics/functions.md
      - Управляющие конструкции: basics/control.md
  - Типы и структуры:
      - Примитивы: types/primitives.md
      - Массивы: types/arrays.md
      - Слайсы: types/slices.md
      - Map и Set: types/maps.md
      - Указатели: types/pointers.md
      - Структуры: types/structs.md
      - Интерфейсы: types/interfaces.md
  - Параллелизм:
      - Горутины: concurrency/goroutines.md
      - Каналы: concurrency/channels.md
      - Select: concurrency/select.md
      - Синхронизация (mutex, sync): concurrency/sync.md
      - Контекст (context): concurrency/context.md
  - Ошибки:
      - Базовая обработка: errors/basic.md
      - Sentinel-ошибки: errors/sentinel.md
      - Обёртка ошибок (error wrapping): errors/wrapping.md
      - Panic и Recover: errors/panic.md
  - Работа со временем: time/timers.md
  - Ввод/вывод: io/streams.md
  - Работа с файлами:
      - Чтение и запись: io/files.md
      - Работа с директорией: io/dirs.md
  - HTTP и веб: http/server.md
  - Модули и пакеты: modules/gomod.md
  - Инструменты разработчика: tools/gotools.md
  - Тестирование и профилирование:
      - Тестирование: testing/testing.md
      - Бенчмарки: testing/benchmarks.md
      - Профилирование: testing/profiling.md
  - Архитектура:
      - Чистая архитектура: architecture/clean.md
      - Сервисы: architecture/services.md
      - Плагины и интерфейсы: architecture/plugins.md
  - Стандартная библиотека: stdlib/overview.md
  - Инфраструктура и сборка: infra/build.md
  - Продвинутое:
      - GC: advanced/gc.md
      - Unsafe: advanced/unsafe.md
      - Reflect: advanced/reflect.md
      - Генерация кода: advanced/generate.md
      - Системное программирование: advanced/sysprog.md
  - Практика: practice/recipes.md
  - 📘 Глоссарий: glossary/glossary.md